### ISSUE TITLE
Lint twig before deploy

### ISSUE THREAD

**Issue by imjared** [patronage/bubs-timber#19]
There should be a way to lint Twig and ensure it's good to go before we push into production.

http://symfony.com/doc/current/templating/syntax.html

**Comment by ccorda** [comment]
Good idea, but I tried this and it was constantly erroring out: https://github.com/Nanigans/gulp-twig-compile

**Comment by ccorda** [comment]
This has been something we've been chasing for awhile, currently using a buggy vscode extension as the best option.

There was a prettyier plugin that has been abandoned, but it looks like someone forked and got it working with modern prettier: 
https://socket.dev/npm/package/@supersoniks/prettier-plugin-twig-melody

Let's use that.
