### ISSUE TITLE
Request for Comment: Fix permissions to write ACF files post-commit or post-pull

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-timber#33]
It seems like in some projects, after every commit, I need to reset ACF folder permissions to get fields to write. Git's "ignore file permissions" option is pretty garbage and never ever ever wants to apply to whole computer, only the repo it runs in. So every time I try to save ACF file, git status says nothing, reset permissions, re-save field group, git status sees it, commit, repeat whole process.

For your consideration: what if we reset those permissions after each pull or each commit with a git post-commit or post-pull task? Since chmod function runs across linux/osx, i think it'd be fine cross-platform. I'm not too worried about windows either.

**Comment by kylehotchkiss** [comment]
An additional option: turn git filemode tracking off from composer.

**Comment by ccorda** [comment]
I'm pro this idea:

http://stackoverflow.com/questions/9985437/chmod-on-git-post-receive
